#!/usr/bin/env bash
# comment
if [ $# -eq 2 ]
then
	record=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
	ip=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk /"$1"/ | cut -d$'\t' -f 4,5)
	echo "The subdomain $2 is a $record record and points to $ip"
else
	record0=$(dig "www.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
	ip0=$(dig "www.$1" | grep -A1 'ANSWER SECTION:' | awk /"$1"/ | cut -d$'\t' -f 4,5)
	echo "The subdomain www is a $record0 record and points to $ip0"
	record1=$(dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
	ip1=$(dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | awk /"$1"/ | cut -d$'\t' -f 4,5)
	echo "The subdomain lb-01 is a $record1 record and points to $ip1"
	record2=$(dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
	ip2=$(dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | awk /"$1"/ | cut -d$'\t' -f 4,5)
	echo "The subdomain web-01 is a $record2 record and points to $ip2"
	record3=$(dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
	ip3=$(dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | awk /"$1"/ | cut -d$'\t' -f 4,5)
	echo "The subdomain web-02 is a $record3 record and points to $ip3"
fi
