#!/usr/bin/env bash
# Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]
my_func () {
	if [ -n "$2" ]
	then
		record=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
		ip=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
		echo "The subdomain $2 is a $record record and points to $ip"
	else
		dig "www.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain www is a "$4" record and points to "$5""}'
		dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain lb-01 is a "$4" record and points to "$5""}'
		dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain web-01 is a "$4" record and points to "$5""}'
		dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain web-02 is a "$4" record and points to "$5""}'
	fi
}
my_func "$1" "$2"
