#!/usr/bin/env bash
# Configure a Ubuntu machine when querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo ufw enable
echo Hello World | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart