#!/usr/bin/env bash
# Configure a Ubuntu machine when querying Nginx at its root 
sudo apt-get update
sudo apt-get install nginx -y
sudo sed -i '/server_name _.*/a  \\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart