#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# - The name of the custom HTTP header must be X-Served-By
# - The value of the custom HTTP header must be the hostname of the server Nginx is running on
# It configures a brand new Ubuntu machine
sudo apt-get update
sudo apt-get install nginx -y
if grep "add_header X-Served-By" /etc/nginx/nginx.conf
then
    :
else
    sudo sed -i "/http {/a \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
fi
sudo service nginx restart
