#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get update
sudo apt install haproxy=2.0.\*
if grep "frontend http_front" /etc/haproxy/haproxy.cfg
then
    :
else
    sudo su
    echo -e "\n\nfrontend http_front\n\tbind *:80\n\tdefault_backend http_back\n" >> /etc/haproxy/haproxy.cfg
    echo -e "backend http_back\n\tbalance roundrobin\n\tserver 3957-web-01 3.91.160.31:80\n\tserver 3957-web-02 54.160.189.223:80" >> /etc/haproxy/haproxy.cfg
    echo -e "ENABLED=1" >> etc/default/haproxy
fi
sudo service haproxy restart
exit

