#!/usr/bin/env bash
# This script displays 'Best School' 10 times, but after 9th iteration displays 'Hi'
i=0
while [ $i -lt 10 ]
do
    printf "Best School\n"
    if [ $i -eq 8 ]
    then
        printf "Hi\n"
    fi
    ((i++))
done
