#!/usr/bin/env bash
# This script displays 'bad luck' for the 4th iteration, 'good luck' for the 8th, 'Best School' for the others
i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 3 ]
    then
        printf "bad luck\n"
    elif [ $i -eq 7 ]
    then
        printf "good luck\n"
    else
        printf "Best School\n"
    fi
    ((i++))
done
