#!/usr/bin/env bash
# This script displays the content of the current directory in a list format
# Only the part of the name after first dash is displayed
for i in *; do echo "$i" | cut -d '-' -f 2; done
