#!/usr/bin/env bash
# This script configures an Ubuntu server with the following requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves 8.8.8.8

cp /etc/hosts hosts_copy

sed -i s/127.0.0.1/127.0.0.2/ hosts_copy

if grep "facebook.com" hosts_copy
then
    :
else
    echo -e "8.8.8.8\tfacebook.com" >> hosts_copy
fi

cp -f hosts_copy /etc/hosts
